vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_images:
           uri_prefix: /images/userImages
           upload_destination: '%kernel.project_dir%/public/images/userImages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        tricks_images:
           uri_prefix: /images/tricksImages
           upload_destination: '%kernel.project_dir%/public/images/tricksImages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true